[package]
name = "game_of_life_rust_wasm"
version = "0.1.0"
authors = ["Tomáš Derner <tomasderner97@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.55"